language: python
python:
 - "3.6"
install:
 - yarn install
 - pip install --no-cache-dir pipenv==11.10.1
 - pipenv install --dev
 - cp settings.travis.py settings_local.py
script:
 - pipenv run invoke test
 - pipenv run invoke docs

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  repo: PlatformOfTrust/translator-skeleton-python